/**
 * Lista członków zespołu Verseo (wszyscy poza headami).
 * Źródło: https://verseo.pl/o-nas/nasz-zespol/
 * Posortowani alfabetycznie po imieniu (polska kolejność).
 */
export const TEAM_MEMBERS = [
  'Adam Kubaszewski',
  'Adam Pruszyński',
  'Adriana Lisiecka',
  'Agnieszka Kwiatkowska',
  'Agnieszka Szymańska',
  'Aleksandra Szulda',
  'Alina Leśniewska',
  'Amadeusz Bąk',
  'Andrzej Simkowski',
  'Aneta Stolcman',
  'Angelika Siemiątkowska',
  'Barbara Jakubowska',
  'Bartłomiej Kiljan',
  'Bartosz Polak',
  'Beata Leśniewicz',
  'Blanka Pisarczyk',
  'Cezary Kutwin',
  'Damian Jędrzejewski',
  'Danuta Janicka',
  'Dariusz Cichocki',
  'Dawid Jesiak',
  'Dominik Kowalewski',
  'Elżbieta Szalska',
  'Emil Leszczak',
  'Filip Jurków',
  'Gabriela Giermek',
  'Hubert Wendzinski',
  'Hubert Wróblewski',
  'Igor Radwański',
  'Inez Białooka',
  'Jacek Smogur',
  'Jagoda Danielewska',
  'Jakub Białczyk',
  'Jakub Kaczmarek',
  'Jakub Łakomy',
  'Jakub Mikołajski',
  'Jakub Wieczorek',
  'Jan Czujko',
  'Jan Zagórski',
  'Jędrzej Swarcewicz',
  'Joanna Gregorczyk',
  'Joanna Hałaszkiewicz',
  'Joanna Michalska-Cerba',
  'Julia Florek',
  'Julia Masłowska',
  'Julia Ostrowska',
  'Justyna Stechlińska',
  'Kamil Bargiel',
  'Kamil Knaś',
  'Kamila Szulc',
  'Katarzyna Książek',
  'Katarzyna Nowakowska',
  'Krzysztof Borzymowski',
  'Krzysztof Prabucki',
  'Łukasz Bobryk',
  'Łukasz Zacharzewski',
  'Maciej Duszyński',
  'Magdalena Król',
  'Małgorzata Figura',
  'Marcin Komar',
  'Marek Cylka',
  'Marek Pankowski',
  'Marika Kachaniak',
  'Mariusz Piskor',
  'Marta Burchard',
  'Marta Starczewska',
  'Mateusz Banaś',
  'Mateusz Tomys',
  'Michalina Simkowska',
  'Michał Drozda',
  'Michał Jarmużek',
  'Michał Majewski',
  'Michał Radoń',
  'Michał Woźniak',
  'Mikołaj Świderski',
  'Milena Guzik',
  'Miłosz Fraszczyk',
  'Monika Dudek-Nowicka',
  'Monika Kaczmarek',
  'Monika Pałczyńska',
  'Monika Wojciechowska',
  'Natalia Kasprzak',
  'Nikodem Szarata',
  'Norbert Zybała',
  'Patryk Stępień',
  'Paulina Błaszkowiak',
  'Paweł Grabowski',
  'Paweł Jankowski',
  'Paweł Królski',
  'Piotr Krzemiński',
  'Piotr Wrzesiński',
  'Pola Chojnacka',
  'Sebastian Gintowt',
  'Szymon Chmielewski',
  'Szymon Nyga',
  'Szymon Stachewicz',
  'Tomasz Jaśkowiak',
  'Tomasz Kolera',
  'Weronika Chorążewicz',
  'Weronika Kaczmarek',
  'Wiktor Kasperuk',
  'Wiktor Ławicki',
  'Witold Chęciński',
  'Zachariasz Kijak',
  'Zbigniew Bober',
  'Zofia Hemmerling',
]

// Deduplikacja na wypadek duplikatów
export const TEAM_MEMBERS_UNIQUE = [...new Set(TEAM_MEMBERS)]

export const CAMPAIGN_GOALS = [
  'Awareness (Świadomość marki)',
  'Consideration (Ruch / Zaangażowanie)',
  'Conversion (Sprzedaż)',
  'Retargeting',
]
