/**
 * Lista członków zespołu Verseo (wszyscy poza headami).
 * Źródło: https://verseo.pl/o-nas/nasz-zespol/
 * Posortowani alfabetycznie po nazwisku (polska kolejność).
 */
export const TEAM_MEMBERS = [
  'Mateusz Banaś',
  'Kamil Bargiel',
  'Amadeusz Bąk',
  'Jakub Białczyk',
  'Inez Białooka',
  'Paulina Błaszkowiak',
  'Zbigniew Bober',
  'Łukasz Bobryk',
  'Krzysztof Borzymowski',
  'Marta Burchard',
  'Witold Chęciński',
  'Szymon Chmielewski',
  'Pola Chojnacka',
  'Weronika Chorążewicz',
  'Dariusz Cichocki',
  'Marek Cylka',
  'Jan Czujko',
  'Jagoda Danielewska',
  'Michał Drozda',
  'Monika Dudek-Nowicka',
  'Maciej Duszyński',
  'Małgorzata Figura',
  'Julia Florek',
  'Miłosz Fraszczyk',
  'Gabriela Giermek',
  'Sebastian Gintowt',
  'Paweł Grabowski',
  'Joanna Gregorczyk',
  'Milena Guzik',
  'Joanna Hałaszkiewicz',
  'Zofia Hemmerling',
  'Barbara Jakubowska',
  'Danuta Janicka',
  'Michał Jarmużek',
  'Tomasz Jaśkowiak',
  'Dawid Jesiak',
  'Damian Jędrzejewski',
  'Filip Jurków',
  'Marika Kachaniak',
  'Jakub Kaczmarek',
  'Monika Kaczmarek',
  'Weronika Kaczmarek',
  'Wiktor Kasperuk',
  'Natalia Kasprzak',
  'Zachariasz Kijak',
  'Bartłomiej Kiljan',
  'Kamil Knaś',
  'Tomasz Kolera',
  'Marcin Komar',
  'Dominik Kowalewski',
  'Magdalena Król',
  'Paweł Królski',
  'Piotr Krzemiński',
  'Katarzyna Książek',
  'Adam Kubaszewski',
  'Cezary Kutwin',
  'Agnieszka Kwiatkowska',
  'Emil Leszczak',
  'Beata Leśniewicz',
  'Alina Leśniewska',
  'Adriana Lisiecka',
  'Jakub Łakomy',
  'Wiktor Ławicki',
  'Michał Majewski',
  'Julia Masłowska',
  'Joanna Michalska-Cerba',
  'Jakub Mikołajski',
  'Katarzyna Nowakowska',
  'Szymon Nyga',
  'Julia Ostrowska',
  'Monika Pałczyńska',
  'Marek Pankowski',
  'Blanka Pisarczyk',
  'Mariusz Piskor',
  'Bartosz Polak',
  'Krzysztof Prabucki',
  'Adam Pruszyński',
  'Michał Radoń',
  'Igor Radwański',
  'Angelika Siemiątkowska',
  'Michalina Simkowska',
  'Andrzej Simkowski',
  'Jacek Smogur',
  'Szymon Stachewicz',
  'Marta Starczewska',
  'Justyna Stechlińska',
  'Patryk Stępień',
  'Aneta Stolcman',
  'Jędrzej Swarcewicz',
  'Elżbieta Szalska',
  'Nikodem Szarata',
  'Kamila Szulc',
  'Aleksandra Szulda',
  'Agnieszka Szymańska',
  'Mikołaj Świderski',
  'Mateusz Tomys',
  'Hubert Wendzinski',
  'Jakub Wieczorek',
  'Monika Wojciechowska',
  'Michał Woźniak',
  'Hubert Wróblewski',
  'Piotr Wrzesiński',
  'Łukasz Zacharzewski',
  'Jan Zagórski',
  'Norbert Zybała',
]

// Deduplikacja na wypadek duplikatów
export const TEAM_MEMBERS_UNIQUE = [...new Set(TEAM_MEMBERS)]

export const CAMPAIGN_GOALS = [
  'Awareness (Świadomość marki)',
  'Consideration (Ruch / Zaangażowanie)',
  'Conversion (Sprzedaż)',
  'Retargeting',
]
