import { useState, useRef } from 'react'
import { resolveModel, costPerImage } from '../lib/modelRouting'
import { cropToAspect, compressToJpeg } from '../lib/imageUtils'

const LOGO_BLOCK_WITH = `LOGO PLACEMENT — reference image provided:
- A reference image of the brand logo is attached as input. Reproduce it EXACTLY as shown — same colors, shapes, letterforms, proportions. Do NOT redraw, stylize, distort, reinterpret or hallucinate the logo in any way.
- Place the logo in top-left corner, clearly visible, within the safe zone.
- Logo size: approximately 18% of banner width, maintain original aspect ratio.
- Ensure sufficient contrast between logo area and background — add subtle light backing if needed.
- The logo must look like it was placed by a graphic designer, not generated by AI.`

const LOGO_BLOCK_WITHOUT = `NO LOGO — do not render any brand logo, logotype, wordmark or brand mark anywhere in the image. The logo will be added manually in post-production. Leave clean empty space in the top-left corner. Do NOT render any placeholder box, dashed border, dotted rectangle, "logo here" text, bracket outline, or any visual indicator of a reserved area — just leave the space genuinely empty and clean.`

export default function GeneratorPanel({ formats, logoDataUrl, brandName, domain }) {
  const [statuses, setStatuses] = useState(() => {
    const s = {}
    formats.forEach((f) => (s[f.id] = { status: 'idle' }))
    return s
  })
  const [previews, setPreviews] = useState({})
  const [doneCount, setDoneCount] = useState(0)
  const [running, setRunning] = useState(false)
  const folderHandleRef = useRef(null)
  const [folderName, setFolderName] = useState(null)
  const abortRef = useRef(null)

  const fsaOk = typeof window !== 'undefined' && 'showDirectoryPicker' in window

  const totalFormats = formats.length
  const totalCost = formats.reduce((s, f) => s + costPerImage(resolveModel(f).type), 0).toFixed(2)
  const progress = totalFormats > 0 ? Math.round((doneCount / totalFormats) * 100) : 0

  const pickFolder = async () => {
    if (!fsaOk) {
      setFolderName('Downloads')
      return
    }
    try {
      folderHandleRef.current = await window.showDirectoryPicker({ mode: 'readwrite' })
      setFolderName(folderHandleRef.current.name)
    } catch {}
  }

  const updateStatus = (id, data) => {
    setStatuses((prev) => ({ ...prev, [id]: data }))
  }

  const generateOne = async (fmt) => {
    updateStatus(fmt.id, { status: 'generating' })

    const model = resolveModel(fmt)
    const useLogo = !!logoDataUrl
    const logoBlock = useLogo ? LOGO_BLOCK_WITH : LOGO_BLOCK_WITHOUT
    const finalPrompt = fmt.prompt.replace('{{LOGO_BLOCK}}', logoBlock)

    const timeoutMs = useLogo ? 180000 : 90000

    try {
      const controller = new AbortController()
      abortRef.current = controller
      const tid = setTimeout(() => controller.abort(), timeoutMs)

      const res = await fetch('/.netlify/functions/generate-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: finalPrompt,
          ar: model.ar,
          modelType: model.type,
          useLogo,
          logoDataUrl: useLogo ? logoDataUrl : undefined,
        }),
        signal: controller.signal,
      })

      clearTimeout(tid)

      if (!res.ok) {
        const errText = await res.text().catch(() => '')
        throw new Error(`HTTP ${res.status}: ${errText.slice(0, 200)}`)
      }

      const data = await res.json()
      const imgUrl = data.imageUrl

      // Fetch the generated image
      let srcBlob = await (await fetch(imgUrl)).blob()

      // Resize if needed
      if (model.needsResize) {
        srcBlob = await cropToAspect(srcBlob, fmt.width, fmt.height)
      }

      // Compress
      const blob = await compressToJpeg(srcBlob)
      const previewUrl = URL.createObjectURL(blob)
      setPreviews((prev) => ({ ...prev, [fmt.id]: previewUrl }))

      // Save file
      const filename = `${domain}_${fmt.width}x${fmt.height}_${fmt.id}.jpg`

      if (folderHandleRef.current) {
        const fh = await folderHandleRef.current.getFileHandle(filename, { create: true })
        const w = await fh.createWritable()
        await w.write(blob)
        await w.close()
      } else {
        const a = document.createElement('a')
        a.href = previewUrl
        a.download = filename
        a.click()
      }

      updateStatus(fmt.id, { status: 'done' })
      setDoneCount((c) => c + 1)
    } catch (e) {
      const msg = e.name === 'AbortError' ? 'Timeout — za długo' : e.message
      updateStatus(fmt.id, { status: 'error', message: msg })
    }
  }

  const generateAll = async () => {
    if (running) return
    setRunning(true)

    for (const fmt of formats) {
      if (statuses[fmt.id]?.status === 'done') continue
      await generateOne(fmt)
    }

    setRunning(false)
  }

  const stopGeneration = () => {
    abortRef.current?.abort()
    setRunning(false)
  }

  return (
    <div>
      {/* Header */}
      <h2 className="text-xl font-bold mb-0.5">Banner Generator — {brandName}</h2>
      <p className="text-sm text-gray-400 mb-3">
        {domain} · Nano Banana (fal.ai) · {totalFormats} grafik · ~${totalCost}
      </p>

      {/* Progress bar */}
      <div className="h-1 bg-gray-200 rounded-full mb-4">
        <div
          className="h-1 bg-brand-orange rounded-full transition-all duration-400"
          style={{ width: `${progress}%` }}
        />
      </div>

      {/* Folder picker */}
      <div className="bg-white rounded-xl p-3.5 mb-3 flex items-center gap-3.5">
        <button
          onClick={pickFolder}
          className="bg-gray-900 text-white rounded-lg px-4 py-2 text-sm font-semibold whitespace-nowrap hover:bg-gray-800 transition-colors"
        >
          📁 Wybierz folder
        </button>
        <span className="text-sm text-gray-500">
          {folderName ? (
            <>→ <strong>{folderName}</strong> <span className="text-xs text-gray-300">({doneCount} zapisanych)</span></>
          ) : (
            fsaOk ? 'Wybierz folder docelowy' : '→ pliki trafią do Downloads'
          )}
        </span>
      </div>

      {/* Format list */}
      <div className="flex flex-col gap-2 mb-4">
        {formats.map((fmt) => {
          const st = statuses[fmt.id]
          const model = resolveModel(fmt)
          const preview = previews[fmt.id]

          return (
            <div
              key={fmt.id}
              className={`bg-white rounded-xl p-3 flex items-center gap-3.5 transition-colors
                ${st.status === 'done' ? 'bg-brand-green-light' : ''}
                ${st.status === 'error' ? 'bg-brand-red-light' : ''}
                ${st.status === 'generating' ? 'bg-orange-50' : ''}`}
            >
              {/* Thumbnail */}
              <div className="w-14 h-14 flex-shrink-0 rounded-md overflow-hidden bg-gray-100 flex items-center justify-center text-xl text-gray-300">
                {preview ? (
                  <img src={preview} alt="" className="w-full h-full object-cover" />
                ) : (
                  '📷'
                )}
              </div>

              {/* Info */}
              <div className="flex-1 min-w-0">
                <div className="text-sm font-semibold truncate">{fmt.label}</div>
                <div className="text-xs text-gray-400 mt-0.5">
                  {fmt.width}×{fmt.height}px · {model.type === 'nb2' ? 'NB2 $0.08' : 'NB Pro $0.15'}
                  {model.needsResize ? ` (${model.ar}→resize)` : ''}
                </div>
              </div>

              {/* Status */}
              <div className="flex-shrink-0 text-sm whitespace-nowrap">
                {st.status === 'done' && <span className="text-brand-green font-semibold">✅ zapisano</span>}
                {st.status === 'error' && (
                  <span className="text-brand-red" title={st.message}>
                    ❌ {st.message?.slice(0, 40)}
                  </span>
                )}
                {st.status === 'generating' && <span className="text-brand-orange font-semibold">⚡ generowanie...</span>}
                {st.status === 'idle' && <span className="text-gray-300">⏳ oczekuje</span>}
              </div>
            </div>
          )
        })}
      </div>

      {/* Generate button */}
      <button
        onClick={running ? stopGeneration : generateAll}
        disabled={!folderName && fsaOk}
        className={`w-full rounded-xl py-4 text-base font-bold transition-colors
          ${running
            ? 'bg-red-600 text-white hover:bg-red-700'
            : 'bg-gray-900 text-white hover:bg-gray-800 disabled:bg-gray-300 disabled:cursor-not-allowed'
          }`}
      >
        {running ? '⏹ Zatrzymaj generowanie' : `⚡ Generuj wszystkie (${totalFormats} grafik)`}
      </button>

      <p className="text-center mt-3 text-xs text-gray-300">
        NB2 native AR → $0.08/img · NB Pro non-native AR → $0.15/img
      </p>
    </div>
  )
}
